package test;

import org.hamcrest.Matchers;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import com.ibm.integration.test.v1.NodeSpy;
import com.ibm.integration.test.v1.SpyObjectReference;
import com.ibm.integration.test.v1.TestSetup;
import com.ibm.integration.test.v1.exception.TestException;

import static com.ibm.integration.test.v1.Matchers.*;
import static org.hamcrest.MatcherAssert.assertThat;

public class TopLevelFlows_TestFlow_TestSubflow_0001_Test {

	/*
	 * TopLevelFlows_TestFlow_TestSubflow_0001_Test
	 * Test generated by IBM App Connect Enterprise Toolkit 12.0.9.0 on Jul 30, 2023 8:32:50 PM
	 * 
	 * Run using
	 *  tdolby@IBM-PF3K066L:~$ mqsibar -c -w ~/tmp/ace-non-application-flows-work-dir -a /mnt/c/Users/684084897/git/ace-non-application-flows/BARfiles/Tests.bar
	 *  Generating runtime objects: '/home/tdolby/tmp/ace-non-application-flows-work-dir/run' ...
	 *  
	 *  BIP8071I: Successful command completion.
	 *  
	 *  tdolby@IBM-PF3K066L:~$ IntegrationServer -w ~/tmp/ace-non-application-flows-work-dir --test-project TopLevelFlows_Test
	 * 
	 */

	@AfterEach
	public void cleanupTest() throws TestException {
		// Ensure any mocks created by a test are cleared after the test runs 
		TestSetup.restoreAllMocks();
	}

	@Test
	public void TopLevelFlows_TestFlow_TestSubflow_TestCase_001() throws TestException {

		// Define the SpyObjectReference
		SpyObjectReference nodeReference = new SpyObjectReference().application("DefaultApplication").messageFlow("TestFlow")
				.node("TestSubflow");

		// Initialise a NodeSpy
		NodeSpy nodeSpy = new NodeSpy(nodeReference);

		// Check that the actual Node name matches the expected name
		assertThat(nodeSpy.nodeName(), Matchers.equalTo("TestSubflow"));

		// Assert the number of times that the node is called
		assertThat(nodeSpy, nodeCallCountIs(0));

		// Assert the terminal propagate count for the message
		assertThat(nodeSpy, terminalPropagateCountIs("Output", 0));

	}

}
