# CI build to validate PR changes before merging

name: ace-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "buildAndTest"
  buildAndTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: tdolby/experimental:ace-full-12.0.8.0-ubuntu
      env:
        LICENSE: accept
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build the application and unit test it
        shell: bash
        run: |
          # This shell has mqsiprofile already loaded
          echo "Starting virtual X server for mqsicreatebar"
          Xvfb -ac :99 &
          sleep 1
          export DISPLAY=:99
          echo "Running build"
          ls -l $GITHUB_WORKSPACE
          mqsicreatebar -data $GITHUB_WORKSPACE -b /tmp/cb-test.bar -cleanBuild -p TopLevelFlows Subflows -o TopLevelFlows/TestFlow.msgflow  -l SubflowStaticLib
          echo "Convert to an application to enable easy unit testing"
